name: master
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: yarn install && yarn build
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build
  convert-via-pandoc:
    runs-on: ubuntu-18.04
    container:
      image: pandoc/latex:2.11.4
    steps:
      - uses: actions/checkout@v2
      - run: mkdir pdf
      - run: mv static/figures/ /
      - run: for f in notes/*.md; do pandoc "$f" --pdf-engine=xelatex -s -o "pdf/$(basename "$f" .md).pdf"; done
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: pdf
